metaDataFormat: yaml
theme: mpaluchowski-2014
baseURL: https://michal.paluchowski.com
permalinks:
  posts: /:slug
  pages: /:slug
languageCode: "en-us"
paginate: 5
googleAnalytics: UA-2971180-9
title: "Michał's Bites"
copyright: Made in Warsaw by Michał Paluchowski. All text and code is under a <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">Creative Commons Attribution 4.0 International License</a>.
params:
  subtitle: Recipes for a software business
  logo:
    path: /img/mpaluchowski.jpg
    alt: Michał Paluchowski
  twitter: mpaluchowski
menu:
  blogs:
    - name: Travel
      url: https://travel.paluchowski.com/
    - name: Triathlon
      url: https://triathlon.paluchowski.com/
