metaDataFormat: yaml
theme: mpaluchowski-2019
baseURL: https://michal.paluchowski.com
permalinks:
  posts: /:filename
  pages: /:filename
  tags: /tag/:slug
  categories: /category/:slug
languageCode: "en-us"
paginate: 10
googleAnalytics: UA-2971180-9
title: "Michał's Bites"
copyright: Made in Warsaw by Michał Paluchowski. All content is under a <a href="https://creativecommons.org/licenses/by/4.0/" rel="license">Creative Commons Attribution 4.0 International License</a>. This template is [open source](https://github.com/mpaluchowski/hugo-mpaluchowski-2019), available under the MIT License.
params:
  subtitle: Recipes for a software business
  twitter: mpaluchowski
  logo:
    path: /img/mpaluchowski.jpg
    alt: Michał Paluchowski
menu:
  blogs:
    - name: Travel
      url: https://travel.paluchowski.com/
  social:
    - name: Twitter
      url: https://twitter.com/mpaluchowski
    - name: GitHub
      url: https://github.com/mpaluchowski
